drivers: soc: atmel: fix the typo error in MACRO definitions
Fix the typo error that cause compilation error in the MACRO definitions.

Error log:
In file included from drivers/soc/atmel/soc.c:18:
drivers/soc/atmel/soc.c:371:45: error: ‘SAMA7D65_D1G_EXID_MATCH’ undeclared here
(not in a function); did you mean ‘SAMA7D65D1G_EXID_MATCH’?
    371 |                  AT91_CIDR_VERSION_MASK(3), SAMA7D65_D1G_EXID_MATCH,
        |                                             ^~~~~~~~~~~~~~~~~~~~~~~

Fixes: 763f91bcf8b7 ("ARM: at91: add support for Software License Levels")
Signed-off-by: Dharma Balasubiramani <dharma.b@microchip.com>