drm/bridge: fix dw-mipi-dsi-mchp compilation error
Fix the following compilation error by including a header and
changing the remove callback's return value from int to void,
this is done by commit 0edb555a65d1 ("platform: Make
platform_driver::remove() return void").

drivers/gpu/drm/bridge/dw-mipi-dsi-mchp.c: In function ‘dw_mipi_dsi_mchp_probe’:
drivers/gpu/drm/bridge/dw-mipi-dsi-mchp.c:438:17: error: implicit declaration of
function ‘of_device_get_match_data’ [-Werror=implicit-function-declaration]
   438 |         cdata = of_device_get_match_data(dsi->dev);
       |                 ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/bridge/dw-mipi-dsi-mchp.c:438:15: warning: assignment to ‘const
struct dw_mipi_dsi_mchp_chip_data *’ from ‘int’ makes pointer from integer
without a cast [-Wint-conversion]
   438 |         cdata = of_device_get_match_data(dsi->dev);
       |               ^
drivers/gpu/drm/bridge/dw-mipi-dsi-mchp.c: At top level:
drivers/gpu/drm/bridge/dw-mipi-dsi-mchp.c:553:27: error: initialization of ‘void
(*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct
platform_device *)’ [-Werror=incompatible-pointer-types]
   553 |         .remove         = dw_mipi_dsi_mchp_remove,
       |                           ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Manikandan Muralidharan <manikandan.m@microchip.com>